#!/usr/bin/env bash
# configure-dicom-uid-root.sh — load LIVERRA_UID_ROOT from AWS Secrets Manager.
#
# Sourced at boot by ml-inference + deploy scripts so every DICOM instance
# generated by LiverRa carries our registered OID root
# (see scripts/ops/acquire-dicom-oid.md).
#
# Usage (in a script):
#   source ./scripts/ops/configure-dicom-uid-root.sh
#   echo "${LIVERRA_UID_ROOT}"
#
# Usage (standalone — prints export line for eval):
#   eval "$(./scripts/ops/configure-dicom-uid-root.sh)"
set -euo pipefail

REGION="${AWS_REGION:-eu-central-1}"
SECRET_ID="${LIVERRA_UID_ROOT_SECRET_ID:-liverra/dicom-uid-root}"

if ! command -v aws >/dev/null 2>&1; then
  echo "[configure-dicom-uid-root] aws CLI not found on PATH" >&2
  exit 1
fi

VALUE="$(
  aws secretsmanager get-secret-value \
    --region "${REGION}" \
    --secret-id "${SECRET_ID}" \
    --query SecretString \
    --output text
)"

if [[ -z "${VALUE}" || "${VALUE}" == "None" ]]; then
  echo "[configure-dicom-uid-root] secret ${SECRET_ID} in ${REGION} is empty" >&2
  echo "[configure-dicom-uid-root] run scripts/ops/acquire-dicom-oid.md first" >&2
  exit 1
fi

# Basic shape check — must start with '1.2.826.0.1.' per Medical Connections format.
if [[ ! "${VALUE}" =~ ^1\.2\.826\.0\.1\..+$ ]]; then
  echo "[configure-dicom-uid-root] secret value '${VALUE}' does not match expected '1.2.826.0.1.XXXXXX'" >&2
  exit 1
fi

export LIVERRA_UID_ROOT="${VALUE}"

# Emit export line so callers can `eval "$(... )"` from outside.
echo "export LIVERRA_UID_ROOT=${VALUE}"
