/**
 * Couinaud palette colour-vision-deficiency (CVD) check (T411).
 *
 * Plain-English:
 *   The 8 Couinaud liver segments are rendered as coloured overlays.
 *   One in 12 men have some form of red/green colour blindness, so
 *   we need to prove that every pair of our segment colours remains
 *   visually distinct after deuteranopia / protanopia / tritanopia
 *   simulation. We use ΔE2000 (perceptual distance) >= 12 as the
 *   safety threshold — below that, two segments can look identical
 *   to a CVD user.
 *
 * Inputs:
 *   - packages/app/src/emr/styles/theme.css — expects CSS custom
 *     properties --liverra-seg-couinaud-{I..VIII} and the dark
 *     variants --liverra-seg-couinaud-{I..VIII}-dark.
 *
 * Outputs:
 *   - Pretty-printed table to stdout.
 *   - Exit 0 on pass, 1 on any pairwise ΔE2000 < 12.
 *
 * References:
 *   - plan.md §UI Conventions → accessibility checklist
 *   - spec.md §NFR (a11y)
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import chroma from 'chroma-js';

const DELTA_E_THRESHOLD = 12;

const SEGMENTS = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII'] as const;

type Segment = (typeof SEGMENTS)[number];
type Variant = 'light' | 'dark';

interface PaletteEntry {
  segment: Segment;
  variant: Variant;
  hex: string;
}

function varName(segment: Segment, variant: Variant): string {
  return variant === 'dark'
    ? `--liverra-seg-couinaud-${segment}-dark`
    : `--liverra-seg-couinaud-${segment}`;
}

function repoRoot(): string {
  return path.resolve(__dirname, '..', '..', '..');
}

function readThemeCss(): string | null {
  const cssPath = path.resolve(repoRoot(), 'packages/app/src/emr/styles/theme.css');
  if (!fs.existsSync(cssPath)) {
    // eslint-disable-next-line no-console
    console.warn(`[palette-cvd-check] theme.css missing at ${cssPath}. Writing placeholder.`);
    try {
      fs.mkdirSync(path.dirname(cssPath), { recursive: true });
      const lines: string[] = [
        '/* LiverRa theme — placeholder generated by palette-cvd-check.ts */',
        '/* The real palette lands in the T080–T090 theme-system tasks. */',
        ':root {',
      ];
      for (let i = 0; i < SEGMENTS.length; i += 1) {
        lines.push(`  ${varName(SEGMENTS[i], 'light')}: hsl(${Math.round((i * 360) / 8)}, 70%, 50%);`);
      }
      for (let i = 0; i < SEGMENTS.length; i += 1) {
        lines.push(`  ${varName(SEGMENTS[i], 'dark')}: hsl(${Math.round((i * 360) / 8)}, 60%, 35%);`);
      }
      lines.push('}', '');
      fs.writeFileSync(cssPath, lines.join('\n'));
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn('[palette-cvd-check] failed to create placeholder theme.css:', err);
      return null;
    }
  }
  return fs.readFileSync(cssPath, 'utf8');
}

function extractVar(css: string, name: string): string | null {
  const pattern = new RegExp(`${name.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&')}\\s*:\\s*([^;]+);`);
  const m = pattern.exec(css);
  if (!m) return null;
  const value = m[1].trim();
  const varMatch = /^var\((--[a-zA-Z0-9_-]+)\)$/.exec(value);
  if (varMatch) {
    return extractVar(css, varMatch[1]);
  }
  return value;
}

function parsePalette(css: string): PaletteEntry[] {
  const entries: PaletteEntry[] = [];
  for (const variant of ['light', 'dark'] as const) {
    for (const segment of SEGMENTS) {
      const raw = extractVar(css, varName(segment, variant));
      if (!raw) continue;
      try {
        const hex = chroma(raw).hex();
        entries.push({ segment, variant, hex });
      } catch {
        // eslint-disable-next-line no-console
        console.warn(`[palette-cvd-check] unparseable colour for ${varName(segment, variant)}: ${raw}`);
      }
    }
  }
  return entries;
}

type CvdMode = 'deuteranopia' | 'protanopia' | 'tritanopia';

/** Machado/Oliveira/Fernandes 2009 severity=1 matrices in linear RGB. */
const CVD_MATRICES: Record<CvdMode, number[][]> = {
  protanopia: [
    [0.152, 1.053, -0.205],
    [0.115, 0.786, 0.099],
    [-0.004, -0.048, 1.052],
  ],
  deuteranopia: [
    [0.367, 0.861, -0.228],
    [0.28, 0.673, 0.047],
    [-0.012, 0.043, 0.969],
  ],
  tritanopia: [
    [1.256, -0.077, -0.179],
    [-0.078, 0.931, 0.148],
    [0.005, 0.691, 0.304],
  ],
};

function simulate(hex: string, mode: CvdMode): string {
  const c = chroma(hex);
  const m = CVD_MATRICES[mode];
  const [r, g, b] = c.rgb();
  const rl = r / 255;
  const gl = g / 255;
  const bl = b / 255;
  const clamp = (v: number): number => Math.min(1, Math.max(0, v));
  const outR = clamp(m[0][0] * rl + m[0][1] * gl + m[0][2] * bl);
  const outG = clamp(m[1][0] * rl + m[1][1] * gl + m[1][2] * bl);
  const outB = clamp(m[2][0] * rl + m[2][1] * gl + m[2][2] * bl);
  return chroma
    .rgb(Math.round(outR * 255), Math.round(outG * 255), Math.round(outB * 255))
    .hex();
}

interface PairResult {
  a: string;
  b: string;
  mode: CvdMode | 'normal';
  deltaE: number;
  pass: boolean;
}

function pairwise(entries: PaletteEntry[]): PairResult[] {
  const results: PairResult[] = [];
  const modes: Array<CvdMode | 'normal'> = ['normal', 'protanopia', 'deuteranopia', 'tritanopia'];
  for (const mode of modes) {
    const simulated = entries.map((e) => ({
      ...e,
      sim: mode === 'normal' ? e.hex : simulate(e.hex, mode),
    }));
    for (let i = 0; i < simulated.length; i += 1) {
      for (let j = i + 1; j < simulated.length; j += 1) {
        const a = simulated[i];
        const b = simulated[j];
        if (a.variant !== b.variant) continue;
        const dE = chroma.deltaE(a.sim, b.sim);
        results.push({
          a: `${a.segment}-${a.variant}`,
          b: `${b.segment}-${b.variant}`,
          mode,
          deltaE: Number(dE.toFixed(2)),
          pass: dE >= DELTA_E_THRESHOLD,
        });
      }
    }
  }
  return results;
}

function printSummary(results: PairResult[]): void {
  const failing = results.filter((r) => !r.pass);
  const passing = results.length - failing.length;
  // eslint-disable-next-line no-console
  console.log(`\nPalette CVD check — ${passing}/${results.length} pairs >= ΔE2000 ${DELTA_E_THRESHOLD}`);
  if (failing.length === 0) {
    // eslint-disable-next-line no-console
    console.log('  OK — all segment pairs remain distinct across CVD simulations.\n');
    return;
  }
  // eslint-disable-next-line no-console
  console.log('  FAIL — pairs below threshold:');
  for (const r of failing) {
    // eslint-disable-next-line no-console
    console.log(`    [${r.mode}] ${r.a} vs ${r.b} — ΔE = ${r.deltaE}`);
  }
}

function main(): void {
  const css = readThemeCss();
  if (!css) {
    // eslint-disable-next-line no-console
    console.error('[palette-cvd-check] theme.css unavailable; skipping (warning only).');
    process.exit(0);
    return;
  }
  const entries = parsePalette(css);
  if (entries.length === 0) {
    // eslint-disable-next-line no-console
    console.warn('[palette-cvd-check] no --liverra-seg-couinaud-* variables found; nothing to check.');
    process.exit(0);
    return;
  }
  const results = pairwise(entries);
  printSummary(results);
  const anyFail = results.some((r) => !r.pass);
  process.exit(anyFail ? 1 : 0);
}

main();
