/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * LiverRa — regenerate via `npm run generate:openapi-client` after edits to
 * specs/001-zero-training-mvp/contracts/api-openapi.yaml. Hand edits are
 * rejected by the pre-commit hook `no-handedit-gen-files` (see
 * scripts/hooks/no-handedit-gen.sh).
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user + tenant + RUO state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                            tenant?: components["schemas"]["Tenant"];
                            permissions?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/ruo-accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record explicit RUO acceptance (FR-031, FR-041) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recorded */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ProblemResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate resumable DICOM upload (FR-001, FR-005) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        filename?: string;
                        size_bytes?: number;
                        sha256?: string;
                    };
                };
            };
            responses: {
                /** @description Upload initiated (tus-style) */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded studies for the caller's tenant (paginated) */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Study"][];
                            next_cursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/studies/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    study_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Study"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kick off analysis for an uploaded study (idempotent per study_id) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        study_id?: string;
                    };
                };
            };
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Analysis"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysis_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Analysis"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        /** Full analysis outputs — parenchyma, segments, vessels, lesions, FLR default */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysis_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            analysis?: components["schemas"]["Analysis"];
                            segmentations?: {
                                /** Format: uuid */
                                id?: string;
                                anatomy_category?: string;
                                anatomy_detail?: string | null;
                                volume_ml?: number;
                                /** Format: uri */
                                mask_url?: string;
                                snomed_code?: string;
                            }[];
                            lesions?: components["schemas"]["Lesion"][];
                            flr_default?: components["schemas"]["FLRCalculation"];
                            confidence_flags?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel queued/running analysis (FR-033a) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysis_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry failed analysis without re-upload (FR-033b) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysis_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New analysis created */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Analysis"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a SurgeonReview (acquires reviewer seat per FR-017a) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        analysis_id?: string;
                    };
                };
            };
            responses: {
                /** @description Seat acquired */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SurgeonReview"];
                    };
                };
                /** @description Seat held by another user; returns holder display_name */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend seat (called every 60s by client) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    review_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Extended */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/mask-refine": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** VISTA3D click-to-refine (FR-015). Local recompute ≤30s. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    review_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        segmentation_id?: string;
                        click_point_voxel?: number[];
                        /** @enum {string} */
                        click_mode?: "add" | "subtract";
                    };
                };
            };
            responses: {
                /** @description Local mask updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            segmentation_id?: string;
                            new_volume_ml?: number;
                            /** Format: uri */
                            mask_url?: string;
                            duration_ms?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/lesion-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MedSAM-2 one-prompt tumor re-segmentation (FR-016) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    review_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        marker_voxel?: number[];
                    };
                };
            };
            responses: {
                /** @description New lesion added to list */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lesion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/classification-override": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reviewer overrides AI classification (spec Edge Cases) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    review_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        lesion_id?: string;
                        /** @enum {string} */
                        new_class?: "hcc" | "icc" | "metastasis" | "fnh" | "hemangioma" | "cyst";
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Override recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/flr": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit a new resection-plane FLR (FR-012/013). Client computes locally; server persists. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    review_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FLRCalculation"];
                };
            };
            responses: {
                /** @description Saved */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FLRCalculation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize the review → triggers Report generation (US5) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    review_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Report generation queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            report_id?: string;
                            /** @enum {string} */
                            status?: "draft" | "finalizing";
                        };
                    };
                };
                401: components["responses"]["StepUpRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    report_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/pacs-push": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push SEG + SR to hospital PACS (FR-026, FR-026a) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    report_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Delivery attempts started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportDelivery"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/pacs-push/{delivery_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                delivery_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    report_id: string;
                    delivery_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retried */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract a finalized Report (FR-027a) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    report_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Retracted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email?: string;
                        /** @enum {string} */
                        role?: "hpb_surgeon" | "radiologist" | "fellow" | "ops" | "compliance" | "dpo";
                        display_name?: string;
                        /** @enum {string} */
                        locale_preference?: "en" | "de" | "ka";
                    };
                };
            };
            responses: {
                /** @description Invite email queued (72h token) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suspended (historical records preserved) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/pacs-destination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        ae_title?: string;
                        host?: string;
                        port?: number;
                        use_tls?: boolean;
                        cert_fingerprint?: string | null;
                    };
                };
            };
            responses: {
                /** @description Saved (after successful C-ECHO pre-flight) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            destination?: components["schemas"]["Tenant"]["pacs_destination"];
                            cecho_round_trip_ms?: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/pacs-destination/echo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reachable?: boolean;
                            round_trip_ms?: number;
                            /** @description PHI-scrubbed */
                            error?: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/studies/{study_id}/delete-request": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a user-submitted case-deletion request (FR-046) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    study_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approved + soft-deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEventSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cross-tenant queue (no PHI) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            queued?: components["schemas"]["Analysis"][];
                            running?: components["schemas"]["Analysis"][];
                            stuck_over_15min?: components["schemas"]["Analysis"][];
                            gpu_utilization_pct?: number;
                            cold_start_rate_last_hour?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/analyses/{analysis_id}/mark-blocked": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    analysis_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Marked blocked — submitting clinician notified */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/mbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active Model Bill of Materials */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            model_name?: string;
                            /** Format: uri */
                            source_url?: string;
                            pinned_commit_sha?: string;
                            license_text_hash_hex?: string;
                            license_name?: string;
                            /** Format: date */
                            integration_date?: string;
                            /** Format: email */
                            approver?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/audit-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    tenant_id: string;
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tamper-evident audit summary with chain verification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events?: components["schemas"]["AuditEventSummary"][];
                            chain_valid?: boolean;
                            chain_first_invalid_sequence_no?: number | null;
                            /** @description hex */
                            merkle_root_for_window?: string;
                            s3_anchor_uris?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/ruo-spot-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default 20 */
                        sample_size?: number;
                    };
                };
            };
            responses: {
                /** @description Sampled artifacts with watermark-region highlighted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            artifact_url?: string;
                            watermark_bbox?: number[];
                            /** @description Reviewer fills post-check */
                            pass?: boolean | null;
                        }[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/claim-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimRegistryEntry"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ClaimRegistryEntry"];
                };
            };
            responses: {
                /** @description Updated (subsequent exports narrow disclaimer scope) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/erasure/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate GDPR Art. 17 erasure for a specific Study (FR-040) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        target_study_id?: string;
                        justification?: string;
                    };
                };
            };
            responses: {
                /** @description Erasure queued (≤60s execution) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            erasure_request_id?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/erasure/requests/{erasure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                erasure_id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    erasure_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (includes confirmation PDF URL once completed) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "requested" | "executing" | "completed" | "rolled_back";
                            tombstone_hash_hex?: string;
                            /** Format: uri */
                            confirmation_pdf_url?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok" | "degraded" | "down";
                            components?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            app_version?: string;
                            pipeline_version?: string;
                            mbom_hash?: string;
                            commit_sha?: string;
                            /** Format: date-time */
                            built_at?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            /** @description MUST NOT contain PHI */
            detail?: string;
            /** Format: uuid */
            tenant_id?: string;
            audit_event_id?: string;
        };
        Tenant: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            display_name?: string;
            /** @enum {string} */
            primary_locale?: "en" | "de" | "ka";
            data_residency_region?: string;
            pacs_destination?: {
                ae_title?: string;
                host?: string;
                port?: number;
                use_tls?: boolean;
                cert_fingerprint?: string | null;
            } | null;
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            display_name?: string;
            /** @enum {string} */
            role?: "hpb_surgeon" | "radiologist" | "fellow" | "admin" | "ops" | "compliance" | "dpo";
            /** Format: uuid */
            tenant_id?: string;
            /** Format: date-time */
            mfa_enrolled_at?: string | null;
            /** Format: date-time */
            ruo_accepted_at?: string | null;
            /** @enum {string} */
            locale_preference?: "en" | "de" | "ka";
            /** @enum {string} */
            theme_preference?: "light" | "dark" | "system";
            /** Format: date-time */
            suspended_at?: string | null;
        };
        Study: {
            /** Format: uuid */
            id?: string;
            study_instance_uid?: string;
            /** Format: uuid */
            uploader_user_id?: string;
            /** Format: date-time */
            upload_started_at?: string;
            /** Format: date-time */
            upload_completed_at?: string | null;
            /** @enum {string} */
            anonymization_status?: "pending" | "passed" | "failed" | "phi_contaminated";
            phase_coverage?: {
                non_contrast?: boolean;
                arterial?: boolean;
                portal_venous?: boolean;
                delayed?: boolean;
            };
            /** @enum {string} */
            ingestion_outcome?: "accepted" | "rejected";
            /** @enum {string|null} */
            ingestion_rejection_reason?: "missing_portal_venous" | "mixed_patient_uid" | "insufficient_coverage" | "partial_coverage_no_override" | "non_liver_ct" | "malformed_dicom" | "phi_burned_in" | null;
            partial_coverage_flag?: boolean;
            phi_contamination_flag?: boolean;
        };
        Analysis: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            study_id?: string;
            /** @enum {string} */
            status?: "queued" | "running" | "complete" | "failed" | "cancelled" | "partial_result";
            /** Format: date-time */
            queued_at?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            pipeline_version?: string;
            cold_start_indicator?: boolean;
            confidence_flags?: string[];
            atypical_anatomy_flags?: string[];
            implausible_output_reason?: string | null;
            timeout_reason?: string | null;
            /** Format: uuid */
            retry_of_analysis_id?: string | null;
            queue_position?: number | null;
            estimated_wait_seconds?: number | null;
        };
        Lesion: {
            /** Format: uuid */
            id?: string;
            couinaud_location?: string;
            longest_diameter_mm?: number;
            volume_ml?: number;
            /** @enum {string} */
            discovery_source?: "ai_detected" | "reviewer_prompted";
            classification?: {
                /** @enum {string} */
                suggested_class?: "hcc" | "icc" | "metastasis" | "fnh" | "hemangioma" | "cyst" | "abstained";
                confidence_vector?: {
                    [key: string]: number;
                };
                abstention_threshold_used?: number;
                temperature_applied?: number;
                model_version?: string;
                reviewer_override_class?: string | null;
            };
        };
        FLRCalculation: {
            /** Format: uuid */
            id?: string;
            plane_normal?: number[];
            plane_offset_mm?: number;
            resected_volume_ml?: number;
            remnant_volume_ml?: number;
            remnant_pct_functional?: number;
            /** @enum {string} */
            author?: "ai_default" | "surgeon_edited";
        };
        SurgeonReview: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            analysis_id?: string;
            /** Format: uuid */
            reviewer_user_id?: string;
            /** Format: date-time */
            seat_held_until?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finalized_at?: string | null;
            edit_count?: number;
            /** Format: uuid */
            is_addendum_of_review_id?: string | null;
        };
        Report: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            analysis_id?: string;
            /** @enum {string} */
            status?: "draft" | "finalized" | "superseded" | "retracted";
            /** Format: date-time */
            finalized_at?: string | null;
            /** Format: uri */
            pdf_url?: string;
            /** Format: uri */
            seg_url?: string;
            /** Format: uri */
            sr_url?: string;
            seg_sop_instance_uid?: string;
            sr_sop_instance_uid?: string;
            /** @constant */
            ruo_watermark_present?: true;
            /** Format: uuid */
            superseded_by_report_id?: string | null;
        };
        ReportDelivery: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            report_id?: string;
            /** @enum {string} */
            artifact_type?: "seg" | "sr";
            destination_ae_title?: string;
            /** @enum {string} */
            status?: "pending" | "sending" | "acknowledged" | "failed" | "manual_fallback";
            retry_count?: number;
            /** @description PHI-scrubbed */
            last_error?: string | null;
            /** Format: date-time */
            next_attempt_at?: string | null;
        };
        AuditEventSummary: {
            id?: string;
            category?: string;
            actor?: string;
            subject?: string;
            /** Format: date-time */
            timestamp?: string;
            /** @enum {string} */
            outcome?: "success" | "denied" | "error";
            chain_sequence_no?: number;
        };
        ClaimRegistryEntry: {
            /** @enum {string} */
            claim_key?: "parenchyma_volumetry" | "flr" | "couinaud_segmentation" | "vessel_identification" | "lesion_detection" | "lesion_classification" | "surgical_planning";
            /** @enum {string} */
            status?: "ruo" | "under_conformity_assessment" | "cleared";
            /** Format: date-time */
            effective_from?: string;
            regulatory_reference?: string | null;
        };
    };
    responses: {
        /** @description Error (RFC 7807) */
        ProblemResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found (also returned for cross-tenant / unauthorized per FR-032a) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 401 with WWW-Authenticate per RFC 9470 */
        StepUpRequired: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
