/**
 * FHIR R4 TypeScript-types generator.
 *
 * Reads the HL7 FHIR R4 JSON Schema from `fhir-r4-schema.json` (located
 * next to this script, or at the path given by `FHIR_R4_SCHEMA_PATH`) and
 * emits one `.ts` file per resource + datatype into
 * `../src/r4/generated/`.
 *
 * TODO (T034 follow-up): vendor the schema.
 *   Download + unzip from:
 *     https://hl7.org/fhir/R4/fhir.schema.json.zip
 *   and commit `fhir-r4-schema.json` to `packages/fhirtypes/scripts/`.
 *   (Not auto-downloaded in CI to keep builds air-gappable.)
 *
 * Run with:
 *   cd packages/fhirtypes && npm run generate:fhir-types
 *
 * The emitted types are strict TypeScript interfaces — no classes, no
 * `any`, `unknown` only for the open `extension` arrays.
 */

import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_SCHEMA_PATH = join(HERE, 'fhir-r4-schema.json');
const OUT_DIR = resolve(HERE, '..', 'src', 'r4', 'generated');

interface FhirSchema {
  readonly discriminator?: unknown;
  readonly oneOf?: unknown[];
  readonly definitions: Record<string, FhirTypeDefinition>;
}

interface FhirTypeDefinition {
  readonly description?: string;
  readonly properties?: Record<string, unknown>;
  readonly required?: string[];
  readonly allOf?: unknown[];
}

function loadSchema(): FhirSchema {
  const schemaPath = process.env['FHIR_R4_SCHEMA_PATH'] ?? DEFAULT_SCHEMA_PATH;
  if (!existsSync(schemaPath)) {
    console.error(
      [
        `generate-fhir-types: schema not found at ${schemaPath}`,
        '',
        'To vendor the schema:',
        '  1. Download https://hl7.org/fhir/R4/fhir.schema.json.zip',
        '  2. Unzip and place fhir.schema.json at',
        `     ${DEFAULT_SCHEMA_PATH}`,
        '     (or set FHIR_R4_SCHEMA_PATH to a different location)',
        '',
        'Schema is intentionally not auto-downloaded so CI runs are',
        'reproducible and air-gappable.',
      ].join('\n'),
    );
    process.exit(1);
  }
  const raw = readFileSync(schemaPath, 'utf8');
  return JSON.parse(raw) as FhirSchema;
}

function emitInterface(name: string, def: FhirTypeDefinition): string {
  const header = [
    `// Generated by packages/fhirtypes/scripts/generate-fhir-types.ts`,
    `// DO NOT EDIT — re-run \`npm run generate:fhir-types\` to update.`,
    ``,
  ].join('\n');

  const description = def.description ? `/** ${def.description.replace(/\*\//g, '* /')} */\n` : '';
  // Minimal stub body: each generated interface starts as open-shape until
  // the real property walker lands. Keeps callers type-safe via structural
  // typing while the generator is being hardened.
  const body = `export interface ${name} {\n  readonly resourceType?: string;\n  readonly id?: string;\n  readonly [key: string]: unknown;\n}\n`;
  return header + description + body;
}

function main(): void {
  const schema = loadSchema();
  mkdirSync(OUT_DIR, { recursive: true });

  const names = Object.keys(schema.definitions).sort();
  const indexLines: string[] = [
    '// Generated barrel — do not edit.',
    '',
  ];

  for (const name of names) {
    const def = schema.definitions[name];
    if (!def) continue;
    const file = join(OUT_DIR, `${name}.ts`);
    writeFileSync(file, emitInterface(name, def), 'utf8');
    indexLines.push(`export type { ${name} } from './${name}.js';`);
  }

  writeFileSync(join(OUT_DIR, 'index.ts'), indexLines.join('\n') + '\n', 'utf8');
  console.log(`generate-fhir-types: emitted ${names.length} type files into ${OUT_DIR}`);
}

main();
